### ISSUE TITLE
X11 shell script doesn't get installed

### ISSUE THREAD

**Issue by astrofrog** [biolab/PyQtTester#2]
I tried installing and using `PyQtTester` using:

```
$ pip install https://github.com/biolab/PyQtTester/archive/master.zip
Collecting https://github.com/biolab/PyQtTester/archive/master.zip
  Downloading https://github.com/biolab/PyQtTester/archive/master.zip
     | 30kB 177kB/s
Installing collected packages: PyQtTester
  Running setup.py install for PyQtTester ... done
Successfully installed PyQtTester-0.1.0
```

but running the PyQtTester command shows that the shell script is not getting installed:

```
$ PyQtTester --help
Traceback (most recent call last):
  File "/Users/tom/miniconda3/envs/dev35/bin/PyQtTester", line 9, in <module>
    load_entry_point('PyQtTester==0.1.0', 'console_scripts', 'PyQtTester')()
  File "/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/pkg_resources/__init__.py", line 549, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2542, in load_entry_point
    return ep.load()
  File "/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2202, in load
    return self.resolve()
  File "/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2208, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/pyqttester.py", line 21, in <module>
    X11_SHELL_SCRIPT = open(join(dirname(__file__), 'x11_subprocess.sh')).read()
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/x11_subprocess.sh'
```

**Comment by kernc** [comment]
Python packaging could be more inconvenient. Probably. Thanks for reporting.

Note, this prog is in fairly initial stages of development and is likely (known to be) broken in all sorts of places. For example, combo boxes' events aren't recorded unless keyboard is used to navigate. Etc.
